-- Helper function to generate numeric ID from string (simple hash for consistency)
-- Or better, we just rely on serial IDs for new rows and logic to match title/slug?
-- No, let's just insert as is. Since 'id' in supabase is likely BIGINT generated by default,
-- we'll let Supabase generate IDs, but we will check 'title' to avoid duplicates.

-- Insert Labuan Bajo
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    '3D2N Explore Labuan Bajo Komodo Dragon using Phinisi Boat',
    'Nikmati petualangan tak terlupakan berlayar di Labuan Bajo selama 3 hari 2 malam. Mengunjungi Pulau Padar, Pulau Komodo, Pink Beach, dan spot snorkeling terbaik dengan kapal Phinisi nyaman ber-AC.',
    'Rp 2.450.000',
    'Nusa Tenggara Timur',
    4.8,
    124,
    12500,
    'https://images.unsplash.com/photo-1596401057633-565652ca65a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1596401057633-565652ca65a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80']),
    '{
        "category": "Open Trip",
        "itinerary": [
            { "day": 1, "activity": "Penjemputan Bandara, Kelor Island, Manjarite, Kalong Island" },
            { "day": 2, "activity": "Padar Island, Pink Beach, Komodo Island, Taka Makassar, Manta Point" },
            { "day": 3, "activity": "Kanawa Island, Kembali ke Pelabuhan & Drop Bandara" }
        ],
        "includes": [
            "Transportasi Bandara - Hotel/Pelabuhan PP",
            "Kapal Phinisi AC selama 3H2M",
            "Makan 7x selama trip",
            "Tiket masuk Taman Nasional Komodo"
        ]
    }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = '3D2N Explore Labuan Bajo Komodo Dragon using Phinisi Boat'
);

-- Insert Bromo Midnight
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    'Private Trip Bromo Midnight Sunrise Hunting via Malang',
    'Saksikan keindahan matahari terbit Bromo yang ikonik tanpa ribet menginap. Penjemputan dari Malang tengah malam, langsung menuju penanjakan dengan Jeep 4WD.',
    'Rp 350.000',
    'Jawa Timur',
    4.9,
    312,
    8200,
    'https://images.unsplash.com/photo-1516690561799-46d8f74f9dab?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1516690561799-46d8f74f9dab?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80']),
    '{
        "category": "Private Trip",
        "itinerary": [
            { "day": 1, "activity": "00:00 Penjemputan di Malang, Perjalanan ke Transit Point" },
            { "day": 1, "activity": "03:00 Tiba di Penanjakan 1, Menunggu Sunrise" },
            { "day": 1, "activity": "06:00 Menuju Kawah Bromo & Pura Luhur Poten" }
        ],
        "includes": ["Transportasi PP Malang - Bromo", "Jeep 4WD Bromo", "Tiket Masuk TNBTS"]
    }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = 'Private Trip Bromo Midnight Sunrise Hunting via Malang'
);

-- Insert Nusa Penida
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    'Explore Nusa Penida West & East with Snorkeling',
    'Jelajahi keindahan Nusa Penida bagian Barat dan Timur dalam satu hari. Kunjungi Kelingking Beach, Diamond Beach, dan snorkeling di Crystal Bay.',
    'Rp 850.000',
    'Bali',
    4.7,
    89,
    15000,
    'https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80']),
    '{ "category": "Available Today" }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = 'Explore Nusa Penida West & East with Snorkeling'
);

-- Insert Raja Ampat
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    'Sailing Trip Raja Ampat Piaynemo Full Day Experience',
    'Surga tersembunyi di Timur Indonesia. Trip eksklusif mengunjungi Piaynemo, Wayag, dan spot diving kelas dunia di Raja Ampat.',
    'Rp 6.500.000',
    'Papua Barat',
    5.0,
    42,
    21000,
    'https://images.unsplash.com/photo-1573790387438-4da905039392?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1573790387438-4da905039392?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80']),
    '{ "category": "Luxury" }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = 'Sailing Trip Raja Ampat Piaynemo Full Day Experience'
);

-- Insert Kawah Ijen
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    'One Day Trip Kawah Ijen Blue Fire Hunting',
    'Pendakian malam hari untuk menyaksikan fenomena api biru (Blue Fire) yang langka di dunia, serta sunrise di kawah asam terbesar.',
    'Rp 250.000',
    'Banyuwangi',
    4.6,
    67,
    5300,
    'https://images.unsplash.com/photo-1605489813292-167825b7ca89?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1605489813292-167825b7ca89?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80']),
    '{ "category": "Open Trip" }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = 'One Day Trip Kawah Ijen Blue Fire Hunting'
);

-- Insert Yogyakarta
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    'Wisata Budaya Yogyakarta Borobudur & Prambanan',
    'Menjelajahi warisan budaya dunia Candi Borobudur dan Prambanan, serta menikmati suasana khas Yogyakarta yang ngangenin.',
    'Rp 450.000',
    'Yogyakarta',
    4.8,
    156,
    9100,
    'https://images.unsplash.com/photo-1598284687063-2391b1066c1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1598284687063-2391b1066c1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80']),
    '{ "category": "Family Trip" }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = 'Wisata Budaya Yogyakarta Borobudur & Prambanan'
);

-- Insert Belitung
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    '3D2N Belitung Island Hopping Laskar Pelangi',
    'Napak tilas Laskar Pelangi dan jelajah pulau-pulau granit eksotis di Belitung. Pantai Tanjung Tinggi, Pulau Lengkuas, dan Danau Kaolin.',
    'Rp 1.850.000',
    'Bangka Belitung',
    4.7,
    98,
    3400,
    'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1589308078059-be1415eab4c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80']),
    '{ "category": "Best Seller" }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = '3D2N Belitung Island Hopping Laskar Pelangi'
);

-- Insert Derawan
INSERT INTO products (title, description, price, location, rating, reviews_count, views_count, image_url, gallery, features)
SELECT 
    'Derawan Islands Paradise 4D3N with Whale Shark',
    'Berenang bersama Whale Shark di Talisayan, melihat ubur-ubur tanpa sengat di Kakaban, dan penyu di Sangalaki. Trip impian para pecinta laut.',
    'Rp 3.200.000',
    'Kalimantan Timur',
    4.9,
    55,
    6700,
    'https://images.unsplash.com/photo-1505993597083-d3f1a9da5e38?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    to_jsonb(ARRAY['https://images.unsplash.com/photo-1505993597083-d3f1a9da5e38?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80']),
    '{ "category": "Water Sports" }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE title = 'Derawan Islands Paradise 4D3N with Whale Shark'
);
