-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Store user data connected to Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone,
  email text,
  full_name text,
  avatar_url text,
  role text default 'user', -- 'admin', 'user', 'sales'
  phone text,
  is_verified boolean default false,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- Turn on Row Level Security
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role, is_verified)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    'user',
    (new.email_confirmed_at is not null)
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. PRODUCTS TABLE (Trips)
create table public.products (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text,
  description text,
  location text,
  price text, -- Storing as text for formatting like "Rp 5.000.000", simple apps often do this
  image_url text,
  category text default 'Open Trip',
  rating numeric default 5.0,
  features jsonb
);

-- RLS for Products
alter table public.products enable row level security;

-- Allow read access to everyone
create policy "Products are viewable by everyone" 
on public.products for select using (true);

-- Allow full access to authenticated users (Simulating Admin for now)
-- In production, you should check for role = 'admin' in profiles
create policy "Admins can manage products" 
on public.products for all using (auth.role() = 'authenticated');


-- 3. NEWS TABLE
create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  excerpt text,
  content text,
  image_url text,
  date date default CURRENT_DATE,
  status text default 'Published' -- 'Published', 'Draft'
);

alter table public.news enable row level security;

create policy "News are viewable by everyone" 
on public.news for select using (true);

create policy "Admins can manage news" 
on public.news for all using (auth.role() = 'authenticated');


-- 4. TRANSACTIONS TABLE
create table public.transactions (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id),
  product_id uuid references public.products(id),
  amount numeric not null,
  status text default 'pending', -- 'pending', 'success', 'cancel'
  items text, -- Description of items bought
  payment_method text
);

alter table public.transactions enable row level security;

-- Admins can view all transactions
create policy "Admins can view all transactions" 
on public.transactions for select using (auth.role() = 'authenticated');

-- Policies would need refining for real user purchase flow


-- DUMMY DATA SEEDING (Optional - Run if you want initial data)

-- Products
insert into public.products (title, slug, location, price, rating, category, description, image_url)
values 
('Sailing Komodo 3D2N', 'sailing-komodo-3d2n', 'Labuan Bajo', 'Rp 2.500.000', 4.9, 'Open Trip', 'Jelajahi keindahan pulau Komodo dan sekitarnya.', 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86'),
('Nusa Penida Day Trip', 'nusa-penida-day-trip', 'Bali', 'Rp 750.000', 4.8, 'Private Trip', 'Trip seharian penuh menikmati pantai kelingking.', 'https://images.unsplash.com/photo-1537996194471-e657df975ab4'),
('Raja Ampat Expedition', 'raja-ampat-expedition', 'Papua', 'Rp 8.500.000', 5.0, 'Open Trip', 'Surga tersembunyi di timur Indonesia.', 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf');

-- News
insert into public.news (title, date, status, image_url)
values
('Tips Traveling Hemat 2025', '2025-01-10', 'Published', 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1'),
('Destinasi Viral Baru di Jawa Timur', '2025-01-15', 'Published', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e');

-- 5. REVIEWS TABLE
create table public.reviews (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_id uuid references public.products(id) on delete cascade,
  user_id uuid references public.profiles(id),
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  user_name text, -- cache name
  avatar_url text -- cache avatar
);

-- RLS for Reviews
alter table public.reviews enable row level security;

-- Allow read access to everyone
create policy "Reviews are viewable by everyone" 
on public.reviews for select using (true);

-- Allow authenticated users to insert reviews
create policy "Authenticated users can insert reviews" 
on public.reviews for insert with check (auth.role() = 'authenticated');
