-- 1. Create banners table
CREATE TABLE IF NOT EXISTS banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create 'banners' storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('banners', 'banners', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Enable RLS on storage.objects (Skipped to avoid permission errors, usually enabled by default)
-- ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for 'banners' bucket

-- Allow Public Read
DROP POLICY IF EXISTS "Public Read Banners" ON storage.objects;
CREATE POLICY "Public Read Banners"
ON storage.objects FOR SELECT
USING ( bucket_id = 'banners' );

-- Allow Authenticated Upload
DROP POLICY IF EXISTS "Authenticated Upload Banners" ON storage.objects;
CREATE POLICY "Authenticated Upload Banners"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'banners' );

-- Allow Authenticated Update
DROP POLICY IF EXISTS "Authenticated Update Banners" ON storage.objects;
CREATE POLICY "Authenticated Update Banners"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'banners' );

-- Allow Authenticated Delete
DROP POLICY IF EXISTS "Authenticated Delete Banners" ON storage.objects;
CREATE POLICY "Authenticated Delete Banners"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'banners' );
